import 'package:flutter/material.dart';

class AppLocalizations {
  final Locale locale;
  AppLocalizations(this.locale);

  static AppLocalizations? of(BuildContext context) {
    return Localizations.of<AppLocalizations>(context, AppLocalizations);
  }

  static const Map<String, Map<String, String>> _localizedValues = {
    'en': {
      'welcome': 'Welcome to AgriGrow!',
      'choose_language': 'What language would you like to use for your farm?',
      'filipino': 'Filipino',
      'english': 'English',
      'kapampangan': 'Kapampangan',
      'continue': 'Continue',
      'how_use': 'How will you use AgriGrow?',
      'pick_role': 'Pick the role that fits your farm business best.',
      'farmer': 'Farmer',
      'farmer_desc': 'I produce crops and want to sell them directly.',
      'logistics': 'Logistics',
      'logistics_desc': 'I own a truck and want to deliver farm produce.',
      'bulk_buyer': 'Bulk Buyer',
      'bulk_buyer_desc': 'I buy for a restaurant, shop, or personal use.',
      'next': 'Next',
      'step_x_of_y': 'Step {current} of {total}',
      'step_farmers': 'Farmers',
      'step_logistics': 'Logistics',
      'drivers_details': 'Driver\'s Details',
      'drivers_details_sub': 'Some basic information to help us get to know you',
      'dob': 'Date of Birth',
      'select_dob_hint': 'Select Date of Birth',
      'gender': 'Gender',
      'select_gender_hint': 'Select Gender',
      'vehicle_details': 'Vehicle Details',
      'vehicle_details_sub': 'Some basic information to help us get to know you',
      'vehicle_type': 'Vehicle Type',
      'select_vehicle_type_hint': 'Select Vehicle Type',
      'vehicle_model': 'Vehicle Model',
      'enter_vehicle_model_hint': 'Enter Vehicle Model',
      'vehicle_brand': 'Vehicle Brand',
      'enter_vehicle_brand_hint': 'Enter Vehicle Brand',
      'year_model': 'Year Model',
      'enter_year_model_hint': 'Enter Year Model',
      'plate_number': 'Plate Number',
      'enter_plate_number_hint': 'Enter Plate Number',
      'vin': 'Vehicle Information Number (VIN)',
      'enter_vin_hint': 'Enter VIN',
      'max_load': 'Maximum Load Capacity',
      'enter_max_load_hint': 'e.g. 1000kg',
      'company_details': 'Company Details',
      'company_details_sub': 'Some basic information to help us get to know you',
      'company_name': 'Company Name',
      'enter_company_name_hint': 'Enter Company Name',
      'biz_reg_no': 'Business Registration Number',
      'enter_biz_reg_no_hint': 'Enter Business Registration Number',
      'company_address': 'Company Address',
      'enter_company_address_hint': 'Enter Company Address',
      'company_contact': 'Company Contact Number',
      'enter_company_contact_hint': 'Enter Contact Number',
      'company_info': 'Company Information',
      'address': 'Address',
      'vehicle_documents': 'Vehicle Documents',
      'company_documents': 'Company Documents',
      'driver_license': 'Driver License',
      'official_receipt': 'Official Receipt (OR)',
      'cert_reg': 'Certification of Registration (CR)',
      'gov_id': 'Government ID',
      'nbi_clearance': 'NBI Clearance',
      'drivers_photo': 'Driver\'s Photo',
      'vehicle_photo': 'Vehicle Photo',
      'biz_permit': 'Business Permit',
      'bir_cert': 'Bureau of Internal Revenue (BIR)',
      'bir_certificate': 'BIR Certificate',
      'dti_sec': 'DTI or SEC Certificate of Registration',
      'national_id': 'National ID',
      'tap_to_take_photo': 'Tap to take photo',
      'upload_license': 'Upload Driver License',
      'upload_or': 'Upload OR',
      'upload_cr': 'Upload CR',
      'upload_gov_id': 'Upload Front & Back',
      'upload_nbi': 'Upload NBI Clearance',
      'upload_driver_photo': 'Upload Driver Photo',
      'upload_utility': 'Upload Utility Bill',
      'upload_vehicle': 'Upload Vehicle',
      'browse': 'Browse',
      'submit_document': 'Submit Document',
      'account_approved_logistics': 'Welcome , Logistics.',
      'help': 'Help',
      'cancel': 'Cancel',
      'authentication': 'Authentication',
      'welcome_back': 'Welcome Back!',
      'login_manage_farmer': 'Log in to manage your farm',
      'login_manage_logistics': 'Log in to manage your logistics',
      'login_manage_bulk_buyer': 'Log in to manage your bulk buying',
      'mobile_number': 'Mobile Number',
      'enter_number': 'Enter your number',
      'enter_otp': 'Enter OTP',
      'resend_otp': 'Resend OTP',
      'otp_sent': 'A verification code has been sent to your mobile.',
      'verify_login': 'Verify & Login',
      'new_to': 'New to AgriGrow? ',
      'sign_up': 'Sign Up',
      'welcome_caps': 'Welcome',
      'mobile_or_email': 'Phone or Email',
      'password_caps': 'Password',
      'forgot_password': 'Forgotten Password?',
      'login_caps': 'Log In',
      'enter_mobile_email': 'Enter your phone number or email',
      'enter_password_hint': 'Enter your password',
      'register_manage_farm': 'Register to manage your farm',
      'email_address': 'Email Address',
      'enter_email_hint': 'Enter your email',
      'contact_number': 'Contact Number',
      'username_caps': 'Username',
      'phone_caps': 'Phone Number',
      'enter_phone_hint': 'Enter your phone number',
      'enter_username_hint': 'Enter your username',
      're_enter_password_caps': 'Re-enter password',
      'continue_caps': 'Continue',
      'user_details': 'User Details',
      'user_details_sub': 'Help us understand who you are',
      'first_name': 'First Name',
      'enter_first_name_hint': 'Enter First Name',
      'middle_name': 'Middle Name',
      'enter_middle_name_hint': 'Enter Middle Name',
      'last_name': 'Last Name',
      'enter_last_name_hint': 'Enter Last Name',
      'province': 'Province',
      'select_province_hint': 'Select Province',
      'municipality': 'Municipality',
      'select_municipality_hint': 'Select Municipality',
      'barangay': 'Barangay',
      'select_barangay_hint': 'Select Barangay',
      'street_address': 'Street Address',
      'enter_street_address_hint': 'Enter Street Address',
      'house_number': 'House Number',
      'enter_house_number_hint': 'Enter House Number',
      'postal_code': 'Postal Code',
      'enter_postal_code_hint': 'Enter Postal Code',
      'country': 'Country',
      'select_country_hint': 'Select Country',
      'region': 'Region',
      'select_region_hint': 'Select Region',
      'municipality_city': 'Municipality/City',
      'house_number_detailed': 'House Number / Street / Detailed Address',
      'farm_details': 'Farm Details',
      'farm_details_sub': 'Information about your farm to help you find customers, you can add more farmland later on',
      'farm_size': 'Farm Size (Hectares)',
      'upload_documents': 'Upload Documents',
      'upload_documents_sub': 'All required documents must be submitted before your account can be verified.',
      'utility_bill': 'Utility Bill :',
      'or_cr': 'OR/CR :',
      'valid_id': 'Valid ID :',
      'owners_address': 'Owner\'s Address :',
      'farm_ownership_docs': 'Farm ownership docs :',
      'uploaded': 'Uploaded',
      'not_uploaded': 'Not Uploaded',
      'submit_application': 'Submit Application',
      'upload_hint': 'Upload JPG/PNG',
      'upload_pdf_hint': 'Upload PDF',
      'doc_verification_hint': 'Utility Bills and Valid IDs help us verify people from malicious actors!',
      'review_submit': 'Review and submit',
      'review_submit_sub': 'Confirm your details before submitting.',
      'review_details': 'Review details',
      'review_details_sub': 'Confirm your details before submitting.',
      'account_details': 'Account details',
      'full_name': 'Full name',
      'submit_caps': 'Submit application',
      'business_details': 'Business details',
      'business_name': 'Business name',
      'business_address': 'Business address',
      'documents_verification': 'Documents verification',
      'step_review': 'Review',
      'role': 'Role',
      'personal_info': 'Personal info',
      'name': 'Name',
      'farm_location': 'Farm location',
      'documents': 'Documents',
      'phone_number': 'Phone number',
      'username': 'Username',
      'personal_details': 'Personal details',
      'farm_size_hectares': 'Farm size (hectares)',
      'check_mailbox': 'Check your mailbox',
      'mailbox_sub': 'A 6-digit verification code will be sent to you via snail mail to your registered address.\nThis may take 5-7 business days.',
      'email_verification_sub': 'A 6-digit verification code has been sent to your email address. Please check your inbox.',
      'enter_verification_code': 'Enter verification code',
      'enter_6_digit_button': 'Enter 6 digit code',
      'complete_welcome': 'Complete',
      'welcome_title': 'Welcome!',
      'account_approved': 'Account Approved!',
      'welcome_farmer': 'Welcome, {name}',
      'required': 'Required',
      'email_required': 'Email is required',
      'invalid_email': 'Invalid email',
      'invalid_phone': 'Phone number must be 11 digits',
      'username_required': 'Username is required',
      'password_min_length': 'Password must be at least 6 characters',
      'passwords_not_match': 'Passwords do not match',
      'enter_6_digit_error': 'Please enter 6-digit code',
      'invalid_code': 'Invalid code. Please try again.',
      'valid_email_error': 'Enter a valid email',
      'done': 'Done',
      'file_uploaded': 'File Uploaded',
      'incomplete': 'Incomplete',
      'hectares_label': 'Hectares',
      'login_success': 'Login Successful!',
      'enter_credentials_error': 'Please enter email/username and password',
      'please_upload_all_docs': 'Please upload all required documents to proceed.',
      'sms_failed': 'Failed to send verification SMS. Please check your API key and balance.',
      'registration_failed': 'Failed to submit application. Please try again.',
      'step_bulk_buyers': 'Bulk Buyers',
      'upload_docs_sub': 'Please upload all the required documents to verify your account.',
      'account_verified': 'Account Verified',
      'verified_documents': 'Verified Documents',
      'view_verified_docs_sub': 'Your documents have been verified. You can view them below.',
      'documents_updated': 'Documents updated successfully.',
      'back_to_profile': 'Back to Profile',
      'finish_registration': 'Finish Registration',
      'doc_verified_notice': 'Your documents have been verified and are now in read-only mode. Use the edit icon to request changes.',
    },
    'fil': {
      'welcome': 'Maligayang pagdating sa AgriGrow!',
      'choose_language': 'Anong wika ang gusto mong gamitin para sa iyong bukid?',
      'filipino': 'Filipino',
      'english': 'Ingles',
      'kapampangan': 'Kapampangan',
      'continue': 'Ipagpatuloy',
      'how_use': 'Paano mo gagamitin ang AgriGrow?',
      'pick_role': 'Pumili ng papel na pinaka-angkop sa iyong negosyo sa bukid.',
      'farmer': 'Magsasaka',
      'farmer_desc': 'Gumagawa ako ng mga pananim at nais kong ibenta ang mga ito nang direkta.',
      'logistics': 'Lohistika',
      'logistics_desc': 'Mayroon akong trak at nais kong maghatid ng mga produkto sa bukid.',
      'bulk_buyer': 'Pakyawan na Mamimili',
      'bulk_buyer_desc': 'Bumibili ako para sa isang restawran, tindahan, o personal na gamit.',
      'next': 'Susunod',
      'step_x_of_y': 'Hakbang {current} ng {total}',
      'step_farmers': 'Magsasaka',
      'step_logistics': 'Lohistika',
      'drivers_details': 'Mga Detalye ng Driver',
      'drivers_details_sub': 'Ilang pangunahing impormasyon upang matulungan kaming makilala ka',
      'dob': 'Petsa ng Kapanganakan',
      'select_dob_hint': 'Piliin ang Petsa ng Kapanganakan',
      'gender': 'Kasarian',
      'select_gender_hint': 'Pumili ng Kasarian',
      'vehicle_details': 'Mga Detalye ng Sasakyan',
      'vehicle_details_sub': 'Ilang pangunahing impormasyon upang matulungan kaming makilala ka',
      'vehicle_type': 'Uri ng Sasakyan',
      'select_vehicle_type_hint': 'Pumili ng Uri ng Sasakyan',
      'vehicle_model': 'Modelo ng Sasakyan',
      'enter_vehicle_model_hint': 'Ipasok ang Modelo ng Sasakyan',
      'vehicle_brand': 'Brand ng Sasakyan',
      'enter_vehicle_brand_hint': 'Ipasok ang Brand ng Sasakyan',
      'year_model': 'Year Model',
      'enter_year_model_hint': 'Ipasok ang Year Model',
      'plate_number': 'Numero ng Plato',
      'enter_plate_number_hint': 'Ipasok ang Numero ng Plato',
      'vin': 'Vehicle Information Number (VIN)',
      'enter_vin_hint': 'Ipasok ang VIN',
      'max_load': 'Maximum Load Capacity',
      'enter_max_load_hint': 'hal. 1000kg',
      'company_details': 'Mga Detalye ng Kumpanya',
      'company_details_sub': 'Ilang pangunahing impormasyon upang matulungan kaming makilala ka',
      'company_name': 'Pangalan ng Kumpanya',
      'enter_company_name_hint': 'Ipasok ang Pangalan ng Kumpanya',
      'biz_reg_no': 'Numero ng Rehistrasyon ng Negosyo',
      'enter_biz_reg_no_hint': 'Ipasok ang Numero ng Rehistrasyon ng Negosyo',
      'company_address': 'Address ng Kumpanya',
      'enter_company_address_hint': 'Ipasok ang Address ng Kumpanya',
      'company_contact': 'Numero ng Pakikipag-ugnayan ng Kumpanya',
      'enter_company_contact_hint': 'Ipasok ang Numero ng Pakikipag-ugnayan',
      'company_info': 'Impormasyon ng Kumpanya',
      'address': 'Address',
      'vehicle_documents': 'Mga Dokumento ng Sasakyan',
      'company_documents': 'Mga Dokumento ng Kumpanya',
      'driver_license': 'Lisensya sa Pagmamaneho',
      'official_receipt': 'Official Receipt (OR)',
      'cert_reg': 'Certification of Registration (CR)',
      'gov_id': 'Government ID',
      'nbi_clearance': 'NBI Clearance',
      'drivers_photo': 'Larawan ng Driver',
      'vehicle_photo': 'Larawan ng Sasakyan',
      'biz_permit': 'Business Permit',
      'bir_cert': 'Bureau of Internal Revenue (BIR)',
      'bir_certificate': 'BIR Certificate',
      'dti_sec': 'DTI o SEC Certificate of Registration',
      'national_id': 'National ID',
      'tap_to_take_photo': 'I-tap para kumuha ng larawan',
      'upload_license': 'I-upload ang Lisensya sa Pagmamaneho',
      'upload_or': 'I-upload ang OR',
      'upload_cr': 'I-upload ang CR',
      'upload_gov_id': 'I-upload ang Harap at Likod',
      'upload_nbi': 'I-upload ang NBI Clearance',
      'upload_driver_photo': 'I-upload ang Larawan ng Driver',
      'upload_utility': 'I-upload ang Utility Bill',
      'upload_vehicle': 'I-upload ang Sasakyan',
      'browse': 'Mag-browse',
      'submit_document': 'Isumite ang Dokumento',
      'account_approved_logistics': 'Maligayang pagdating, Logistics.',
      'help': 'Tulong',
      'cancel': 'Kanselahin',
      'authentication': 'Authentication',
      'welcome_back': 'Maligayang Pagbabalik!',
      'login_manage_farmer': 'Mag-log in upang pamahalaan ang iyong bukid',
      'login_manage_logistics': 'Mag-log in upang pamahalaan ang iyong lohistika',
      'login_manage_bulk_buyer': 'Mag-log in upang pamahalaan ang iyong maramihang pagbili',
      'mobile_number': 'Numero ng Mobile',
      'enter_number': 'Ipasok ang iyong numero',
      'enter_otp': 'Ipasok ang OTP',
      'resend_otp': 'I-resend ang OTP',
      'otp_sent': 'Isang verification code ang naipadala sa iyong mobile.',
      'verify_login': 'Verify at Mag-login',
      'new_to': 'Bago sa AgriGrow? ',
      'sign_up': 'Mag-sign up',
      'welcome_caps': 'Maligayang Pagdating',
      'mobile_or_email': 'Telepono o Email',
      'password_caps': 'Password',
      'forgot_password': 'Nakalimutan ang Password?',
      'login_caps': 'Mag-log in',
      'enter_mobile_email': 'Ipasok ang iyong numero ng telepono o email',
      'enter_password_hint': 'Ipasok ang iyong password',
      'register_manage_farm': 'Mag-rehistro upang pamahalaan ang iyong bukid',
      'email_address': 'Email Address',
      'enter_email_hint': 'Ipasok ang iyong email',
      'username_caps': 'Username',
      'phone_caps': 'Numero ng Telepono',
      'enter_phone_hint': 'Ipasok ang iyong numero ng telepono',
      'enter_username_hint': 'Ipasok ang iyong username',
      're_enter_password_caps': 'Ipasok muli ang password',
      'continue_caps': 'Ipagpatuloy',
      'user_details': 'Mga Detalye ng User',
      'user_details_sub': 'Tulungan kaming maunawaan kung sino ka',
      'first_name': 'Pangalan',
      'enter_first_name_hint': 'Ipasok ang Pangalan',
      'middle_name': 'Gitnang Pangalan',
      'enter_middle_name_hint': 'Ipasok ang Gitnang Pangalan',
      'last_name': 'Apelyido',
      'enter_last_name_hint': 'Ipasok ang Apelyido',
      'province': 'Lalawigan',
      'select_province_hint': 'Pumili ng Lalawigan',
      'municipality': 'Bayan/Lungsod',
      'select_municipality_hint': 'Pumili ng Bayan/Lungsod',
      'barangay': 'Barangay',
      'select_barangay_hint': 'Pumili ng Barangay',
      'street_address': 'Address ng Kalye',
      'enter_street_address_hint': 'Ipasok ang Address ng Kalye',
      'house_number': 'Numero ng Bahay',
      'enter_house_number_hint': 'Ipasok ang numero ng iyong bahay',
      'postal_code': 'Postal Code',
      'enter_postal_code_hint': 'Ipasok ang iyong postal code',
      'country': 'Bansa',
      'select_country_hint': 'Pumili ng Bansa',
      'region': 'Rehiyon',
      'select_region_hint': 'Pumili ng Rehiyon',
      'municipality_city': 'Bayan/Lungsod',
      'house_number_detailed': 'Numero ng Bahay / Kalye / Detalyadong Address',
      'farm_details': 'Mga Detalye ng Bukid',
      'farm_details_sub': 'Impormasyon tungkol sa iyong bukid upang matulungan kang makahanap ng mga customer, maaari kang magdagdag ng higit pang lupang sakahan mamaya',
      'farm_size': 'Sukat ng Bukid (Ektarya)',
      'upload_documents': 'Mag-upload ng mga Dokumento',
      'upload_documents_sub': 'Ang lahat ng kinakailangang dokumento ay dapat isumite bago ma-verify ang iyong account.',
      'utility_bill': 'Utility Bill :',
      'or_cr': 'OR/CR :',
      'valid_id': 'Valid ID :',
      'owners_address': 'Adres ng May-ari :',
      'farm_ownership_docs': 'Mga dokumento ng pagmamay-ari ng bukid :',
      'uploaded': 'Na-upload na',
      'not_uploaded': 'Hindi Na-upload',
      'submit_application': 'Isumite ang Aplikasyon',
      'upload_hint': 'Mag-upload ng JPG/PNG',
      'upload_pdf_hint': 'Mag-upload ng PDF',
      'doc_verification_hint': 'Ang mga Utility Bill at mga Valid ID ay tumutulong sa amin na i-verify ang mga tao mula sa mga nakakahamak na aktor!',
      'review_submit': 'Suriin at isumite',
      'review_submit_sub': 'Kumpirmahin ang iyong mga detalye bago isumite.',
      'review_details': 'Suriin ang mga detalye',
      'review_details_sub': 'Kumpirmahin ang iyong mga detalye bago isumite.',
      'account_details': 'Mga detalye ng account',
      'full_name': 'Buong pangalan',
      'submit_caps': 'Isumite ang aplikasyon',
      'business_details': 'Mga detalye ng negosyo',
      'business_name': 'Pangalan ng negosyo',
      'business_address': 'Address ng negosyo',
      'documents_verification': 'Beripikasyon ng mga dokumento',
      'step_review': 'Suriin',
      'role': 'Papel',
      'personal_info': 'Personal na impormasyon',
      'name': 'Pangalan',
      'farm_location': 'Lokasyon ng bukid',
      'documents': 'Mga dokumento',
      'phone_number': 'Numero ng telepono',
      'username': 'Username',
      'personal_details': 'Personal na mga detalye',
      'farm_size_hectares': 'Sukat ng bukid (ektarya)',
      'missing': 'Nawawala',
      'check_mailbox': 'Suriin ang iyong mailbox',
      'mailbox_sub': 'Isang 6-digit na verification code ang ipadadala sa iyo sa pamamagitan ng snail mail sa iyong rehistradong address.\nMaaaring tumagal ito ng 5-7 araw ng negosyo.',
      'email_verification_sub': 'Isang 6-digit na verification code ang ipinadala sa iyong email address. Mangyaring suriin ang iyong inbox.',
      'enter_verification_code': 'Ipasok ang Verification Code',
      'enter_6_digit_button': 'Ipasok ang 6 Digit Code',
      'complete_welcome': 'Kumpleto',
      'welcome_title': 'Maligayang Pagdating!',
      'account_approved': 'Naaprubahan na ang Account!',
      'welcome_farmer': 'Maligayang Pagdating, {name}',
      'required': 'Kinakailangan',
      'email_required': 'Kinakailangan ang Email',
      'username_required': 'Kinakailangan ang Username',
      'password_min_length': 'Ang password ay dapat na hindi bababa sa 6 na character',
      'passwords_not_match': 'Hindi tumutugma ang mga password',
      'enter_6_digit_error': 'Mangyaring ipasok ang 6-digit na code',
      'invalid_code': 'Maling code. Pakisubukang muli.',
      'invalid_phone': 'Ang numero ng telepono ay dapat na 11 digit',
      'valid_email_error': 'Magpasok ng wastong email',
      'done': 'Tapos Na',
      'file_uploaded': 'Na-upload na ang File',
      'incomplete': 'Hindi Kumpleto',
      'hectares_label': 'Ektarya',
      'login_success': 'Tagumpay ang pag-login!',
      'enter_credentials_error': 'Mangyaring ipasok ang email/username at password',
      'please_upload_all_docs': 'Mangyaring i-upload ang lahat ng kinakailangang dokumento para magpatuloy.',
      'sms_failed': 'Nabigong ipadala ang verification SMS. Pakisuri ang iyong API key at balanse.',
      'registration_failed': 'Nabigong isumite ang aplikasyon. Pakisubukang muli.',
      'step_bulk_buyers': 'Mamimili ng Maramihan',
      'upload_docs_sub': 'Mangyaring i-upload ang lahat ng kinakailangang dokumento upang ma-verify ang iyong account.',
      'account_verified': 'Beripikadong Account',
      'verified_documents': 'Mga Beripikadong Dokumento',
      'view_verified_docs_sub': 'Na-verify na ang iyong mga dokumento. Maaari mong tingnan ang mga ito sa ibaba.',
      'documents_updated': 'Matagumpay na na-update ang mga dokumento.',
      'back_to_profile': 'Bumalik sa Profile',
      'finish_registration': 'Tapusin ang Rehistrasyon',
      'doc_verified_notice': 'Ang iyong mga dokumento ay na-verify na at nasa read-only mode. Gamitin ang edit icon para humiling ng mga pagbabago.',
    },
    'pam': {
      'welcome': 'Malaus ko pu king AgriGrow!',
      'choose_language': 'Nanu ya pung salita ing buring yung gamitan para king kekayung marangle?',
      'filipino': 'Filipino',
      'english': 'Ingles',
      'kapampangan': 'Kapampangan',
      'continue': 'Ituluy',
      'how_use': 'Makananu ye pung gamitan ing AgriGrow?',
      'pick_role': 'Pili ya pu ing papil a pekabage king negosyu yu king marangle.',
      'farmer': 'Ortelanu',
      'farmer_desc': 'Gagawa kung tanaman at buri kung isali la reti ng diretsu.',
      'logistics': 'Lojistiku',
      'logistics_desc': 'Atin kung trak at buri kung mag-deliver gamit king marangle.',
      'bulk_buyer': 'Maniasali king Dakal',
      'bulk_buyer_desc': 'Sasaluku para king restaurant, tindahan, o sariling gamit.',
      'next': 'Tuki',
      'step_x_of_y': 'Sulung {current} king {total}',
      'step_farmers': 'Ortelanu',
      'step_logistics': 'Lohistiku',
      'drivers_details': 'Detalye ning Driver',
      'drivers_details_sub': 'Ilang pangunahing impormasyon para mas makilala daka',
      'dob': 'Alldo ning Kebaitan',
      'select_dob_hint': 'Mamili yang Aldo ning Kebaitan',
      'gender': 'Kasarian',
      'select_gender_hint': 'Mamili yang Kasarian',
      'vehicle_details': 'Detalye ning Sasakyan',
      'vehicle_details_sub': 'Ilang pangunahing impormasyon para mas makilala daka',
      'vehicle_type': 'Uri ning Sasakyan',
      'select_vehicle_type_hint': 'Mamili yang Uri ning Sasakyan',
      'vehicle_model': 'Modelo ning Sasakyan',
      'enter_vehicle_model_hint': 'Iparungut ya ing Modelo ning Sasakyan',
      'vehicle_brand': 'Brand ning Sasakyan',
      'enter_vehicle_brand_hint': 'Iparungut ya ing Brand ning Sasakyan',
      'year_model': 'Year Model',
      'enter_year_model_hint': 'Iparungut ya ing Year Model',
      'plate_number': 'Numeru ning Plato',
      'enter_plate_number_hint': 'Iparungut ya ing Numeru ning Plato',
      'vin': 'Vehicle Information Number (VIN)',
      'enter_vin_hint': 'Iparungut ya ing VIN',
      'max_load': 'Maximum Load Capacity',
      'enter_max_load_hint': 'e.g. 1000kg',
      'company_details': 'Detalye ning Kumpanya',
      'company_details_sub': 'Ilang pangunahing impormasyon para mas makilala daka',
      'company_name': 'Lagyu ning Kumpanya',
      'enter_company_name_hint': 'Iparungut ya ing Lagyu ning Kumpanya',
      'biz_reg_no': 'Numeru ning Rehistrasyun ning Negosyu',
      'enter_biz_reg_no_hint': 'Iparungut ya ing Numeru ning Rehistrasyun ning Negosyu',
      'company_address': 'Address ning Kumpanya',
      'enter_company_address_hint': 'Iparungut ya ing Address ning Kumpanya',
      'company_contact': 'Numeru ning Pamakipag-ugnayan ning Kumpanya',
      'enter_company_contact_hint': 'Iparungut ya ing Numeru ning Pamakipag-ugnayan',
      'company_info': 'Impormasyun ning Kumpanya',
      'address': 'Address',
      'vehicle_documents': 'Dokumintu ning Sasakyan',
      'company_documents': 'Dokumintu ning Kumpanya',
      'driver_license': 'Lisensya king Pamagmanehu',
      'official_receipt': 'Official Receipt (OR)',
      'cert_reg': 'Certification of Registration (CR)',
      'gov_id': 'Government ID',
      'nbi_clearance': 'NBI Clearance',
      'drivers_photo': 'Larawan ning Driver',
      'vehicle_photo': 'Larawan ning Sasakyan',
      'biz_permit': 'Business Permit',
      'bir_cert': 'Bureau of Internal Revenue (BIR)',
      'bir_certificate': 'BIR Certificate',
      'dti_sec': 'DTI o SEC Certificate of Registration',
      'national_id': 'National ID',
      'tap_to_take_photo': 'I-tap para kumuha ng larawan',
      'upload_license': 'I-upload ing Lisensya king Pamagmanehu',
      'upload_or': 'I-upload ing OR',
      'upload_cr': 'I-upload ing CR',
      'upload_gov_id': 'I-upload ing Arap at Lalam',
      'upload_nbi': 'I-upload ing NBI Clearance',
      'upload_driver_photo': 'I-upload ing Larawan ning Driver',
      'upload_utility': 'I-upload ing Utility Bill',
      'upload_vehicle': 'I-upload ing Sasakyan',
      'browse': 'Mamili',
      'submit_document': 'Isumite ing Dokumintu',
      'account_approved_logistics': 'Malaus ka, Logistics.',
      'help': 'Saup',
      'cancel': 'Kansela',
      'authentication': 'Authentication',
      'welcome_back': 'Mayap a Pagdatung Pasibayu!',
      'login_manage_farmer': 'Mag-log in para pamanihala king kekayung marangle',
      'login_manage_logistics': 'Mag-log in para pamanihala king kekayung lohistiku',
      'login_manage_bulk_buyer': 'Mag-log in para pamanihala king kekayung pamanyaling dakal',
      'mobile_number': 'Numeru ng Mobile',
      'enter_number': 'Iparungut ya ing kekayung numeru',
      'enter_otp': 'Iparungut ya ing OTP',
      'resend_otp': 'I-padala pasibayu ing OTP',
      'otp_sent': 'Atin pung verification code a mipadala king kekayung mobile.',
      'verify_login': 'Verify at Mag-login',
      'new_to': 'Bayu kayu pu king AgriGrow? ',
      'sign_up': 'Mag-sign up',
      'welcome_caps': 'Malaus Ka',
      'mobile_or_email': 'Telepono o Email',
      'password_caps': 'Password',
      'forgot_password': 'Milingwan ya ing Password?',
      'login_caps': 'Mag-log in',
      'enter_mobile_email': 'Iparungut ya ing kekayung numero ning telepono o email',
      'enter_password_hint': 'Iparungut ya ing kekayung password',
      'register_manage_farm': 'Mag-rehistru para pamanihala king kekayung marangle',
      'email_address': 'Email Address',
      'enter_email_hint': 'Iparungut ya ing kekayung email',
      'username_caps': 'Username',
      'phone_caps': 'Numeru ning Telepono',
      'enter_phone_hint': 'Iparungut ya ing kekayung numero ning telepono',
      'enter_username_hint': 'Iparungut ya ing kekayung username',
      're_enter_password_caps': 'Iparungut pasibayu ing password',
      'continue_caps': 'Ituluy',
      'user_details': 'Detalye ning User',
      'user_details_sub': 'Saupan mu kami bang aintindian mi nung ninu ka',
      'first_name': 'Lagyu',
      'enter_first_name_hint': 'Iparungut ya ing Lagyu',
      'middle_name': 'Gitnang Lagyu',
      'enter_middle_name_hint': 'Iparungut ya ing Gitnang Lagyu',
      'last_name': 'Apelyidu',
      'enter_last_name_hint': 'Iparungut ya ing Apelyidu',
      'province': 'Lalawigan',
      'select_province_hint': 'Mamili yang Lalawigan',
      'municipality': 'Balen/Lungsod',
      'select_municipality_hint': 'Mamili yang Balen/Lungsod',
      'barangay': 'Barangay',
      'select_barangay_hint': 'Mamili yang Barangay',
      'street_address': 'Address ning Dalan',
      'enter_street_address_hint': 'Iparungut ya ing Address ning Dalan',
      'house_number': 'Numeru ning Bale',
      'enter_house_number_hint': 'Iparungut ya ing numeru ning kekayung bale',
      'postal_code': 'Postal Code',
      'enter_postal_code_hint': 'Iparungut ya ing kekayung postal code',
      'country': 'Bansa',
      'select_country_hint': 'Mamili yang Bansa',
      'region': 'Rehiyon',
      'select_region_hint': 'Mamili yang Rehiyon',
      'municipality_city': 'Balen/Lungsod',
      'house_number_detailed': 'Numeru ning Bale / Dalan / Detalyadong Address',
      'farm_details': 'Detalye ning Marangle',
      'farm_details_sub': 'Impormasyun tungkul king kekayung marangle bang saupan dakayung makapanintun sasaluk, malyari kayung mandagdag marangle potang kayi',
      'farm_size': 'Sukat ning Marangle (Ektarya)',
      'upload_documents': 'Mag-upload Dokumintu',
      'upload_documents_sub': 'Dapat isumite la ngan reng kailangang dokumintu bayu ya ma-verify ing kekayung account.',
      'utility_bill': 'Utility Bill :',
      'or_cr': 'OR/CR :',
      'valid_id': 'Valid ID :',
      'owners_address': 'Adres ning May-ari :',
      'farm_ownership_docs': 'Dokumintu ning pamamay-ari ning marangle :',
      'uploaded': 'Miy-upload ne',
      'not_uploaded': 'Aliwa Miy-upload',
      'submit_application': 'Isumite ing Aplikasyun',
      'upload_hint': 'Mag-upload JPG/PNG',
      'upload_pdf_hint': 'Mag-upload PDF',
      'doc_verification_hint': 'Reng Utility Bills at Valid ID sasaup la kekami bang i-verify la reng tau!',
      'review_submit': 'Suriin at isumite',
      'review_submit_sub': 'Siguraduan la reng detalye bayu isumite.',
      'review_details': 'Suriin la reng detalye',
      'review_details_sub': 'Siguraduan la reng detalye bayu isumite.',
      'account_details': 'Detalye ning account',
      'full_name': 'Buung lagyu',
      'submit_caps': 'Isumite ing aplikasyun',
      'business_details': 'Detalye ning negosyu',
      'business_name': 'Lagyu ning negosyu',
      'business_address': 'Address ning negosyu',
      'documents_verification': 'Beripikasyun da reng dokumintu',
      'step_review': 'Suriin',
      'role': 'Papil',
      'personal_info': 'Personal a impormasyun',
      'name': 'Lagyu',
      'farm_location': 'Lokasyun ning marangle',
      'documents': 'Deng dokumintu',
      'phone_number': 'Numeru ning telepono',
      'username': 'Username',
      'personal_details': 'Personal a detalye',
      'farm_size_hectares': 'Sukat ning marangle (ektarya)',
      'missing': 'Mawawala',
      'check_mailbox': 'Suriin mu ing kekang mailbox',
      'mailbox_sub': 'Atin 6-digit a verification code a ipadala keka snail mail king kekang registered address.\nMalyari yang lumabas 5-7 business days.',
      'email_verification_sub': 'Atin 6-digit a verification code a mipadala king kekang email address. Pakisuri ya ing kekang inbox.',
      'enter_verification_code': 'Iparungut ya ing Verification Code',
      'enter_6_digit_button': 'Iparungut ya ing 6 Digit Code',
    },
  };

  String translate(String key) {
    return _localizedValues[locale.languageCode]?[key] ?? _localizedValues['en']?[key] ?? key;
  }
}

class AppLocalizationsDelegate extends LocalizationsDelegate<AppLocalizations> {
  const AppLocalizationsDelegate();

  @override
  bool isSupported(Locale locale) {
    return ['en', 'fil', 'pam'].contains(locale.languageCode);
  }

  @override
  Future<AppLocalizations> load(Locale locale) async {
    return AppLocalizations(locale);
  }

  @override
  bool shouldReload(covariant LocalizationsDelegate<AppLocalizations> old) {
    return false;
  }
}

extension LocalizationExtension on BuildContext {
  String loc(String key) {
    return AppLocalizations.of(this)?.translate(key) ?? key;
  }
}